[package]
name = "tidyup"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.70"
clap = { version = "4.2.5", features = ["derive"] }
serde = "1.0.160"
walkdir = "2.3.3"
